/**
 * Builds data/geo/us-map.ts: a simplified, pre-projected US outline (Albers USA,
 * 975×610, from us-atlas) plus projected metro positions. Run: npm run build:map
 * The site ships only the resulting path strings; no mapping library at runtime.
 */
import fs from "fs";
import { feature, mesh } from "topojson-client";
import { presimplify, simplify } from "topojson-simplify";
import { geoAlbersUsa, geoPath } from "d3-geo";

const raw = JSON.parse(fs.readFileSync(new URL("../node_modules/us-atlas/states-albers-10m.json", import.meta.url)));
const topo = simplify(presimplify(raw), 1.2);
const path = geoPath().digits(0);
const nation = path(feature(topo, topo.objects.nation));
const states = path(mesh(topo, topo.objects.states, (a, b) => a !== b));

// Metro centres (lon, lat). us-atlas's Albers file uses scale 1300, translate [487.5, 305].
const COORDS = {
  sf: [-122.42, 37.77], sj: [-121.89, 37.34], nyc: [-74.01, 40.71], sea: [-122.33, 47.61], bos: [-71.06, 42.36],
  la: [-118.24, 34.05], sd: [-117.16, 32.72], dc: [-77.04, 38.91], hnl: [-157.86, 21.31], mia: [-80.19, 25.76],
  den: [-104.99, 39.74], chi: [-87.63, 41.88], aus: [-97.74, 30.27], dal: [-96.8, 32.78], hou: [-95.37, 29.76],
  atl: [-84.39, 33.75], phx: [-112.07, 33.45], phl: [-75.17, 39.95], pdx: [-122.68, 45.52], msp: [-93.27, 44.98],
  sac: [-121.49, 38.58], bal: [-76.61, 39.29], ral: [-78.64, 35.78], clt: [-80.84, 35.23], nsh: [-86.78, 36.16],
  slc: [-111.89, 40.76], lv: [-115.14, 36.17], orl: [-81.38, 28.54], tpa: [-82.46, 27.95], det: [-83.05, 42.33],
  col: [-83.0, 39.96], pit: [-80.0, 40.44], cle: [-81.69, 41.5], cin: [-84.51, 39.1], stl: [-90.2, 38.63],
  kc: [-94.58, 39.1], ind: [-86.16, 39.77], mil: [-87.91, 43.04], sa: [-98.49, 29.42], okc: [-97.52, 35.47],
  abq: [-106.65, 35.08], boi: [-116.2, 43.62], ric: [-77.44, 37.54], nol: [-90.07, 29.95], lou: [-85.76, 38.25],
  mem: [-90.05, 35.15], bhm: [-86.8, 33.52], oma: [-95.93, 41.26], dsm: [-93.61, 41.59], mad: [-89.4, 43.07],
};
const proj = geoAlbersUsa().scale(1300).translate([487.5, 305]);
const points = Object.fromEntries(Object.entries(COORDS).map(([id, c]) => [id, proj(c).map((v) => Math.round(v * 10) / 10)]));

const out = `/* Generated by scripts/build-map.mjs from us-atlas (ISC). Do not edit by hand. */
export const US_MAP = { width: 975, height: 610 } as const;
export const US_NATION = ${JSON.stringify(nation)};
export const US_STATE_BORDERS = ${JSON.stringify(states)};
/** Projected metro positions in the same 975×610 space. */
export const METRO_XY: Record<string, [number, number]> = ${JSON.stringify(points)};
`;
fs.writeFileSync(new URL("../data/geo/us-map.ts", import.meta.url), out);
console.log("nation", nation.length, "borders", states.length, "metros", Object.keys(points).length);
